### ISSUE TITLE
文档标题不够明显

### ISSUE THREAD

**Issue by jareguo** [fireball-x/docs-zh#13]
我个人认为现在的标题放在左边，不够显眼，因为浏览文章时我们一般习惯性的把目光放在右侧，如果标题在左上角常常会误以为没有标题。
![image](https://cloud.githubusercontent.com/assets/1503156/6594377/9aa7e4e6-c81b-11e4-84ad-363e746f3b8a.png)

**Comment by nantas** [comment]
重构以后已修复
