### ISSUE TITLE
文档网站重构

### ISSUE THREAD

**Issue by nantas** [fireball-x/docs-zh#22]
目前的文档网站是用 hexo.io 旧版的网站主题改的，api 文档生成方面直接使用了 hexo 的 yuidoc 插件，当时没费什么力气，目前在网站可用的情况下，我们需要一边继续完善添加内容，一边考虑解决以下问题：

- Hexo 升级到 3.0 以后，不再继续支持 Yuidoc 导入插件，由于这个原因我们没有升级，但这样早晚会难以继续维护
- 目前文档网站的 SEO 有不小的问题，swifttype 引擎没办法正确的抓取页面内容
- 自动生成的 API 文档无法经过预处理插件生成 atom.xml 等 feed，影响了在这些页面上加载论坛评论的功能
- 我们需要替换外观和主题到我们自己的设计
- 为了用户使用方便，考虑把文档网站彻底分成中文和英文两个独立的站点，分别更新
- 考虑模仿 atom.io/docs 加入版本号选择功能，至少应该支持 api 分版本号查询

由于目前是骑驴找马的状况，所以可以不那么着急的好好规划一个方案，甚至是自己写一套方案来解决上述这些问题，基本需求如下：

- 要能够部署在 gh-pages 上
- 支持搜索功能（静态或动态都可以）
- 使用 md 作为源文件，文档的版本管理作为 public repo 放在 github 上
- 支持代码高亮

欢迎大家提供意见，综合上述需求应该采用什么技术方案，顺便评估一下开发的工作量和难度。

@fireball-x/docs @fireball-x/server @fireball-x/owners

**Comment by nantas** [comment]
这篇有点意思：使用 react + webpack 制作纯静态网站 http://braddenver.com/blog/2015/react-static-site.html

**Comment by yorkie** [comment]
`expressjs.com`的例子我觉得也挺符合我们以下需求的：

1. 能够部署在`gh-pages`上
2. 使用`markdown`作为文章的源文件

至于：a) 支持搜索功能，这个可以自己实现不难，b) 支持代码高亮，这个功能是用在搜索结果进行高亮，还是像下面这种：

```js
function () {
  // Hola Firebox Team
}
```

这种应该属于markdown的解析/生成的部分，可以沿用Github的flovered markdown的格式，使用仓库`marked`，具体见：

* https://github.com/chjj/marked#highlight
* https://github.com/chjj/marked#gfm

网站的源代码在：https://github.com/strongloop/expressjs.com 确认使用这个方案 可以基于它的基础上进行**二次开发**。

**Comment by nantas** [comment]
好的，我去评估一下

**Comment by nantas** [comment]
express 网站是用 Jekyll 直接生成的，结构相对简单，当然 jekyll 的可靠性目前还是static site generator 里数一数二的。如果我们采用这个方案需要面对两个问题：

- windows 用户在本地配置开发环境和进行测试比较困难
- Jekyll 的插件系统因为要使用 ruby，所以对我们来说比较难扩展

第一个问题可以尝试使用 cloud9、codeanywhere 等服务来解决，第二个问题可以尝试在 jekyll build 之前或之后通过 gulp 任务的方式完成我们需要的 html 页面，比如从 yuidoc 的 json 中解析内容生成 api 文档页面（这里会有一定工作量，因为 api 文档里要求有内部链接关系，可以从一个类跳到另一个类）

其他选择：

升级 hexo 到3.0以上，然后自己更新一下 hexo yuidoc 插件，同时继续研究 SEO 方面的问题。

另外一个可能的选择是 harpjs.com，不过除了是用 js 的系统以外，从受众和可靠性上都无法和 jekyll 相比。

**Comment by yorkie** [comment]
同意，我的话会选择hexo升到3.0的方案，这个方案应该是代价成本相对比较少的。不过我并没有查找到3.0不支持YUIDoc的Changlogs诶，使用插件的话应该是直接使用hexo-yuidoc这个模组吧。SEO的问题我觉得我们可以自己fork一个分支来自己开发，维护的问题我觉得基本出现Bug解一下，要加什么我们团队自己需要的特性也可以直接我们自己实现就OK。(当然我们fix了SEO问题之后，也可以给hexo提PR请求合并)

相反地，如果我们内部需要添加某些特别的feature的时候，要去反馈给hexo社区反而会比较慢。我以后也可以专门负责这个模组的维护。

**Comment by nantas** [comment]
好的，我会先测试一下 hexo3.0的基本情况和 hexo-yuidoc 的新版本兼容升级（目前因为作者本人不用 yuidoc 了，所以 hexo-yuidoc 没有更新hexo 3.0的支持。）

**Comment by yorkie** [comment]
Ok

**Comment by nantas** [comment]
- [ ] 研究应该用 post 还是 page 作为文档的单位
- [ ] 升级 hexo-yuidoc 到 hexo 3.0 支持
- [ ] 完善 hexo-yuidoc 的文档内链接
- [ ] 确认界面设计和布局
- [ ] 完善导航链接和菜单

**Comment by nantas** [comment]
hexo 3.0 front-matter 中的 permalink 无法覆盖 _config.yml 中设置的 bug：https://github.com/hexojs/hexo/issues/1110

**Comment by nantas** [comment]
重构基本完成，api 文档生成的工作在 fireball-x/dev#496 里继续
